"""Managed gitignore blocks for generated Sonde state."""

from __future__ import annotations

import re
from pathlib import Path

SONDE_BLOCK_PREFIX = "sonde managed"


def ensure_managed_gitignore_block(
    gitignore_path: Path,
    *,
    block_name: str,
    comment: str,
    entries: list[str],
) -> bool:
    """Create or update a named managed block in a .gitignore file."""
    start = f"# --- {SONDE_BLOCK_PREFIX}: {block_name} ---"
    end = f"# --- /{SONDE_BLOCK_PREFIX}: {block_name} ---"
    block_lines = [start, comment, *entries, end]
    block = "\n".join(block_lines) + "\n"

    existing = gitignore_path.read_text(encoding="utf-8") if gitignore_path.exists() else ""
    normalized = existing.replace("\r\n", "\n")
    pattern = re.compile(rf"{re.escape(start)}\n.*?\n{re.escape(end)}\n?", re.DOTALL)

    if pattern.search(normalized):
        updated = pattern.sub(block, normalized)
    else:
        prefix = normalized
        if prefix and not prefix.endswith("\n"):
            prefix += "\n"
        if prefix and not prefix.endswith("\n\n"):
            prefix += "\n"
        updated = prefix + block

    if updated == normalized:
        return False

    gitignore_path.parent.mkdir(parents=True, exist_ok=True)
    gitignore_path.write_text(updated, encoding="utf-8")
    return True


def ensure_sonde_workspace_ignore(root: Path) -> bool:
    """Ensure .sonde/.gitignore ignores generated workspace state."""
    return ensure_managed_gitignore_block(
        root / ".sonde" / ".gitignore",
        block_name="workspace",
        comment="# Generated by sonde — do not commit",
        entries=[
            "brief.md",
            "brief.meta.json",
            "skills.json",
            "focus",
        ],
    )


def ensure_runtime_asset_ignore(project_root: Path) -> bool:
    """Ensure project .gitignore ignores generated runtime assets."""
    return ensure_managed_gitignore_block(
        project_root / ".gitignore",
        block_name="runtime-assets",
        comment="# Generated by sonde setup — local runtime assets",
        entries=[
            ".claude/skills/",
            ".claude/agents/",
            ".cursor/rules/",
            ".codex/skills/",
        ],
    )
