-- Close artifact lifecycle gaps between metadata rows and Supabase Storage.
-- New writes must carry checksums and namespaced storage paths.
-- Blob deletes are queued for privileged reconciliation through the Storage API.

ALTER TABLE artifacts
    ADD CONSTRAINT artifacts_checksum_required
    CHECK (checksum_sha256 IS NOT NULL) NOT VALID;

ALTER TABLE artifacts
    ADD CONSTRAINT artifacts_storage_path_matches_parent
    CHECK (
        (experiment_id IS NOT NULL AND storage_path LIKE experiment_id || '/%')
        OR (finding_id IS NOT NULL AND storage_path LIKE finding_id || '/%')
        OR (direction_id IS NOT NULL AND storage_path LIKE direction_id || '/%')
    ) NOT VALID;

CREATE TABLE artifact_delete_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id TEXT NOT NULL UNIQUE,
    storage_path TEXT NOT NULL,
    bucket_id TEXT NOT NULL DEFAULT 'artifacts',
    reason TEXT NOT NULL DEFAULT 'artifact_row_deleted',
    queued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    processed_at TIMESTAMPTZ,
    last_error TEXT
);

CREATE INDEX idx_artifact_delete_queue_pending
    ON artifact_delete_queue (processed_at, queued_at);

CREATE INDEX idx_artifact_delete_queue_storage_path
    ON artifact_delete_queue (storage_path);

ALTER TABLE artifact_delete_queue ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION enqueue_artifact_delete()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF OLD.storage_path IS NOT NULL AND OLD.storage_path <> '' THEN
        INSERT INTO artifact_delete_queue (artifact_id, storage_path, bucket_id, reason)
        VALUES (OLD.id, OLD.storage_path, 'artifacts', 'artifact_row_deleted')
        ON CONFLICT (artifact_id) DO NOTHING;
    END IF;
    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS artifacts_after_delete_enqueue ON artifacts;

CREATE TRIGGER artifacts_after_delete_enqueue
    AFTER DELETE ON artifacts
    FOR EACH ROW
    EXECUTE FUNCTION enqueue_artifact_delete();
